import Head from 'next/head'
import Link from 'next/link'
import Script from 'next/script'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>COADING HUNTER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script></Script>
      <nav className={styles.mainnav}>
        <ul>
          <Link href=''><li>Home</li></Link>
          <Link href='/about'><li>About</li></Link>
          <Link href='/blog'><li>Blog</li></Link>
          <Link href='/contact'><li>Contact</li></Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
        COADING HUNTER
        </h1>

        <p className={styles.description}>
         A Blog For Hunting Coder..
        </p>
        <div className="bloges">
          <div className="blogitem">
            <h1>ABOUT NEXT-JS</h1>
            <p>THAT'S Javascript FramWork....</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created By <div className={styles.created}> &nbsp; JNSHIROYA</div>
        </a>
      </footer>
    </div>
  )
}
